### ISSUE TITLE
Problem of PV attachment with VM located in two differents zones

### ISSUE THREAD

**Issue by Bizyroth** [outscale/osc-bsu-csi-driver#819] opened 2024-09-18 13:06 UTC
/kind bug

Hello

**What happened?**

We declare some Vm in the cloudgouv-eu-west-1a. We declare a StorageClass and installed the csi driver. It works well, PVC declare PV that was created on Outscale.

Recently, we declare a new VM but in the cloudgouv-eu-west-1b. But PVC still create PV on the zone A. Due to the system of label on node and nodeAffinity on pv, pv cannot be attached to the VM.

But this will not solve another issues, all our PV will be on the zone A so if we want some replication on different zone, it is currently impossible.

**What you expected to happen?**

PV created by a PVC are on the same zone as the node where the PVC is attached.

**How to reproduce it (as minimally and precisely as possible)?**

1. Deploy a cluster with worker on zone A
2. Configure the StorageClass and the CSI driver
3. Create PVC attached on a pod running on a VM in zone A
4. Add a VM located in zone B inside the cluster
5. Create PVC attached on a pod running on the VM located in zone B

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: v1.26.10
Kustomize Version: v4.5.7
Server Version: v1.24.8+rke2r1

- Driver version:
annotations:
    meta.helm.sh/release-name: osc-bsu-csi-driver
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/instance: osc-bsu-csi-driver
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: osc-bsu-csi-driver
    app.kubernetes.io/version: v1.2.4
    helm.sh/chart: osc-bsu-csi-driver-1.5.0

**Comment by outscale-hmi** [comment] 2024-10-03 13:59
Hello 
you need to ensure that PVCs are dynamically provisioned in the same zone as the VM (node) requesting the storage.

1- Use allowedTopologies in Your StorageClass:

You can configure your StorageClass to support provisioning PVs in different zones by defining topology constraints. This allows the storage to be provisioned in a zone that matches the requesting node. Specifically, adding allowedTopologies will ensure that the PV is provisioned in a specific zone that matches the zone of the pod.

2- Set volumeBindingMode to WaitForFirstConsumer:

Setting volumeBindingMode to WaitForFirstConsumer ensures that the PV is not created until a pod requests it. This means k8s will know which zone the pod is scheduled in, and it will then provision the volume in the appropriate zone.

Example:
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: bsu-sc
provisioner: bsu.csi.outscale.com
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.bsu.csi.outscale.com/zone
    values:
        - cloudgouv-eu-west-1a
        - cloudgouv-eu-west-1b
So,  if you list both zones (cloudgouv-eu-west-1a and cloudgouv-eu-west-1b) under allowedTopologies in your StorageClass and set the volumeBindingMode to WaitForFirstConsumer, Kubernetes will create the Persistent Volume (PV) in the same zone as the requesting pod.

Feel free to reach out if you still have any issues or need more help.

**Comment by outscale-hmi** [comment] 2024-10-21 13:19
I will close this issue for now, feel free to reopen it if the problem is still remaining

**Closed by outscale-hmi** 2024-10-21 13:19 UTC
